[tool.poetry]
name = "btp"
version = "0.1.0"
description = "Machine Learning based Video Surveillance"
authors = ["Kugelblitz25 <vighneshnayak203@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
opencv-contrib-python = "^4.10.0"
matplotlib = "^3.9.2"
ultralytics = "^8.2.90"
fastapi = "^0.114.0"
uvicorn = "^0.30.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
